/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Javier Garcia Garcia <javigarciavlc@gmail.com>
 */
public class VistaAdministrador extends javax.swing.JFrame {

    String name;
    String fecha;  //Fecha actual para mostrarsela al usuario
    String hora;  //Hora actual para mostrarsela al usuario

    /**
     * Creates new form VistaAdministrador
     */
    public VistaAdministrador(String usuario, String fechaactual, String horaactual) {
        initComponents();
        name = usuario;   //recuperamos el nombre del usuario que ha entrado
        textuser.setText(name);  //mostramos el nombre del usuario
        fecha = fechaactual;
        textfecha.setText(fecha);
        hora = horaactual;
        texthora.setText(hora);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonañadir = new javax.swing.JButton();
        botonborrar = new javax.swing.JButton();
        botonproyecto = new javax.swing.JButton();
        textuser = new java.awt.Label();
        textfecha = new java.awt.Label();
        texthora = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        botonproyecto1 = new javax.swing.JButton();
        botonusuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MENU ADMINISTRADOR");

        botonañadir.setText("Añadir usuario");
        botonañadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonañadirActionPerformed(evt);
            }
        });

        botonborrar.setText("Borrar usuario");
        botonborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonborrarActionPerformed(evt);
            }
        });

        botonproyecto.setText("Asignar proyecto");
        botonproyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonproyectoActionPerformed(evt);
            }
        });

        textuser.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textuser.setText("Usuario");

        textfecha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textfecha.setText("Fecha");

        texthora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        texthora.setText("Hora");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botonproyecto1.setText("Crear proyecto");
        botonproyecto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonproyecto1ActionPerformed(evt);
            }
        });

        botonusuarios.setText("Mostrar Usuarios");
        botonusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonusuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textfecha, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(texthora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(textuser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonañadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonborrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonproyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonproyecto1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(botonusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textuser, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(texthora, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonañadir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonproyecto1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonañadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonañadirActionPerformed


        VistaAñadirusuario va = new VistaAñadirusuario();
        va.setVisible(true);  //Lanzamos el menu del administrador


    }//GEN-LAST:event_botonañadirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.setVisible(false);  //cerramos el menu usuario
        VistaAcceder v = new VistaAcceder();
        v.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonborrarActionPerformed

        VistaBorrarusuario vb = new VistaBorrarusuario();
        vb.setVisible(true);  //Lanzamos el menu del administrador

    }//GEN-LAST:event_botonborrarActionPerformed

    private void botonproyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonproyectoActionPerformed

        VistaAsignarproyecto vp = new VistaAsignarproyecto();
        vp.setVisible(true);  //Lanzamos el menu del administrador

    }//GEN-LAST:event_botonproyectoActionPerformed

    private void botonproyecto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonproyecto1ActionPerformed

        VistaCrearproyecto vp = new VistaCrearproyecto();
        vp.setVisible(true);  //Lanzamos el menu del administrador

    }//GEN-LAST:event_botonproyecto1ActionPerformed

    private void botonusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonusuariosActionPerformed

        Vistamostrarusuarios vu = new Vistamostrarusuarios();
        vu.setVisible(true);  //Lanzamos el menu del administrador
        
    }//GEN-LAST:event_botonusuariosActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonañadir;
    private javax.swing.JButton botonborrar;
    private javax.swing.JButton botonproyecto;
    private javax.swing.JButton botonproyecto1;
    private javax.swing.JButton botonusuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label textfecha;
    private java.awt.Label texthora;
    private java.awt.Label textuser;
    // End of variables declaration//GEN-END:variables
}
